version : '3'

services:
  api-solid-pg:
    container_name: api-solid-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=apisolid
  financial_backend:
    build: 
      context: .
    container_name: financial_backend
    ports:
      - 3333:3333
    depends_on:
      - api-solid-pg