version : '3'

services:
  financial_backend-pg:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - financial 
  financial_backend:
    build: 
      context: .
    container_name: financial_backend
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@financial_backend-pg:5432/financial
      - NODE_ENV=dev
      - PORT=3333
    depends_on:
      - financial_backend-pg
    networks:
      - financial
networks:
  financial:
    driver: bridge
